"""init after refactor

Revision ID: 3a724f4ccee0
Revises: 
Create Date: 2025-07-04 23:52:07.382377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a724f4ccee0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('ladel', sa.String(), nullable=False))
    op.drop_index(op.f('ix_Notes_id'), table_name='Notes')
    op.drop_index(op.f('ix_Notes_uuid'), table_name='Notes')
    op.drop_column('Notes', 'created_at')
    op.drop_column('Notes', 'updated_at')
    op.drop_column('Notes', 'uuid')
    op.drop_column('Notes', 'is_active')
    op.drop_column('Notes', 'label')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('Notes', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Notes', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Notes', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('Notes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Notes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_Notes_uuid'), 'Notes', ['uuid'], unique=True)
    op.create_index(op.f('ix_Notes_id'), 'Notes', ['id'], unique=False)
    op.drop_column('Notes', 'ladel')
    # ### end Alembic commands ###
