"""refactor

Revision ID: 7a4586112c74
Revises: 
Create Date: 2025-07-05 14:23:29.223908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4586112c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('label', sa.String(), nullable=False))
    op.drop_column('Notes', 'ladel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('ladel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Notes', 'label')
    # ### end Alembic commands ###
